### ISSUE TITLE
Update contact under https://openmdm.org/contact/

### ISSUE THREAD

**Issue by BrainInSight** [EclipseFdn/openmdm.org#8]
**Describe the bug**
Ralph Müller is still listed as contact person, but Ralph left the Eclipse Foundation earlier this year

**To Reproduce**
Visit the website :-) https://openmdm.org/contact/

**Expected behavior**
Please replace with my (Michael Plagge) contact info

**Comment by linkfang** [comment]
Hi @BrainInSight ,

Please preview the changes here:
https://deploy-preview-10--eclipsefdn-openmdm.netlify.app/contact/
